project:
  type: website

website:
  title: "非英語圏における Julia ユーザのための技術"
  navbar:
    left:
      - href: slide/slide.qmd
        text: slide

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true